### ISSUE TITLE
Add endpoint for adding/deleting/updating teachers on the subject

### ISSUE THREAD

**Issue by just-hoshinon** [fictadvisor/fictadvisor-api#271]
If we have a problem with discipline teachers of group, we need to make raw requests to the database.

Probable solution: create an endpoint that will have body with teacher id, role and discipline id (or subject id and group id instead)

**Comment by Hahhhayam** [comment]
23/03

**Comment by Hahhhayam** [comment]
UPD: 26/03

**Comment by Hahhhayam** [comment]
Have one question about pipe realization:
I realize data Body validation in Pipes, because all fields should already consist in DB.
The question:
I have two pipes, for create and update endpoints. In general, both of them validate same fields. in one of them they are just optional. I can leave this pipes, but can also join them in one (but i think its overload the functional of this pipe).
What I should do?
@just-hoshinon @Kivanval
